import os
import time
import logging
import threading
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv
import json

load_dotenv()

VAULT_PATH = Path(os.getenv('VAULT_PATH',
    'E:\\Python Projects\\Personal AI Employee Hackathon 0\\AI_Employee_Vault'))
DRY_RUN = os.getenv('DRY_RUN', 'true').lower() == 'true'

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(
            VAULT_PATH / 'Logs' / f'{datetime.now().strftime("%Y-%m-%d")}.log',
            encoding='utf-8'
        ),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

def update_dashboard(needs_action_count: int, done_count: int, plans_count: int):
    dashboard_path = VAULT_PATH / 'Dashboard.md'
    content = f'''# 🤖 AI Employee Dashboard
*Last Updated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}*

---

## 📊 Status
- **AI Employee Status:** 🟢 Active
- **Last Check:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
- **Pending Actions:** {needs_action_count}
- **Completed Today:** {done_count}
- **Active Plans:** {plans_count}
- **DRY RUN Mode:** {DRY_RUN}

---

## 🔔 Needs Your Attention
{"🔴 " + str(needs_action_count) + " items need your attention!" if needs_action_count > 0 else "✅ Nothing needs attention right now"}

---

## 📁 Vault Status
- /Needs_Action: {needs_action_count} items
- /Done: {done_count} items
- /Plans: {plans_count} plans

---

## 🔒 Security
- DRY RUN: {DRY_RUN}
- All actions logged to /Logs
- Approval required for sensitive actions
- LinkedIn posts require manual approval

---
*Generated by AI Employee v2.0 — Silver Tier*
'''
    dashboard_path.write_text(content, encoding='utf-8')
    logger.info('Dashboard updated')

def count_files(folder: Path) -> int:
    if not folder.exists():
        return 0
    return len([f for f in folder.iterdir() if f.is_file()])

def log_action(action_type: str, details: str, result: str):
    log_file = VAULT_PATH / 'Logs' / \
        f'{datetime.now().strftime("%Y-%m-%d")}.json'
    logs = []
    if log_file.exists():
        try:
            logs = json.loads(log_file.read_text(encoding='utf-8'))
        except:
            logs = []
    logs.append({
        "timestamp": datetime.now().isoformat(),
        "action_type": action_type,
        "actor": "ai_employee",
        "details": details,
        "dry_run": DRY_RUN,
        "result": result
    })
    log_file.write_text(json.dumps(logs, indent=2), encoding='utf-8')

def start_gmail_watcher():
    try:
        from gmail_watcher import GmailWatcher
        watcher = GmailWatcher()
        watcher.run()
    except Exception as e:
        logger.error(f'Gmail watcher failed: {e}')

def start_filesystem_watcher():
    try:
        from filesystem_watcher import start_filesystem_watcher
        start_filesystem_watcher()
    except Exception as e:
        logger.error(f'Filesystem watcher failed: {e}')

def start_reasoning_loop():
    try:
        from reasoning_engine import reasoning_loop
        reasoning_loop()
    except Exception as e:
        logger.error(f'Reasoning loop failed: {e}')

def start_linkedin_watcher():
    try:
        from linkedin_poster import watch_approved_linkedin
        watch_approved_linkedin()
    except Exception as e:
        logger.error(f'LinkedIn watcher failed: {e}')

def main():
    logger.info('='*50)
    logger.info('AI Employee v2.0 Starting — Silver Tier')
    logger.info(f'Vault: {VAULT_PATH}')
    logger.info(f'DRY RUN: {DRY_RUN}')
    logger.info('='*50)

    # Ensure all folders exist
    for folder in ['Needs_Action', 'Done', 'Inbox', 'Logs',
                   'Plans', 'Pending_Approval', 'Approved', 'Rejected']:
        (VAULT_PATH / folder).mkdir(parents=True, exist_ok=True)

    # Start all watchers in background threads
    threads = [
        threading.Thread(target=start_gmail_watcher,
            daemon=True, name='GmailWatcher'),
        threading.Thread(target=start_filesystem_watcher,
            daemon=True, name='FilesystemWatcher'),
        threading.Thread(target=start_reasoning_loop,
            daemon=True, name='ReasoningLoop'),
        threading.Thread(target=start_linkedin_watcher,
            daemon=True, name='LinkedInWatcher'),
    ]

    for thread in threads:
        thread.start()
        logger.info(f'{thread.name} started')

    # Main loop
    while True:
        try:
            needs_action_count = count_files(VAULT_PATH / 'Needs_Action')
            done_count = count_files(VAULT_PATH / 'Done')
            plans_count = count_files(VAULT_PATH / 'Plans')
            update_dashboard(needs_action_count, done_count, plans_count)
            log_action(
                'dashboard_update',
                f'Pending:{needs_action_count} Done:{done_count}',
                'success'
            )
        except Exception as e:
            logger.error(f'Orchestrator error: {e}')
        time.sleep(60)

if __name__ == '__main__':
    main()
    