import os
import json
import logging
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv
import requests

load_dotenv()

VAULT_PATH = Path(os.getenv('VAULT_PATH',
    'E:\\Python Projects\\Personal AI Employee Hackathon 0\\AI_Employee_Vault'))
GROQ_API_KEY = os.getenv('GROQ_API_KEY', '')
DRY_RUN = os.getenv('DRY_RUN', 'true').lower() == 'true'

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def read_vault_file(filename: str) -> str:
    """Read a file from the vault"""
    filepath = VAULT_PATH / filename
    if filepath.exists():
        return filepath.read_text(encoding='utf-8')
    return ""

def get_needs_action_items() -> list:
    """Get all items in Needs_Action folder"""
    needs_action = VAULT_PATH / 'Needs_Action'
    items = []
    
    for file in needs_action.glob('*.md'):
        content = file.read_text(encoding='utf-8')
        items.append({
            'filename': file.name,
            'content': content[:500]
        })
    
    return items

def call_groq(prompt: str) -> str:
    """Call Groq API for reasoning"""
    if not GROQ_API_KEY:
        logger.warning('No GROQ_API_KEY found — using mock response')
        return f"Mock plan created at {datetime.now()}"
    
    try:
        response = requests.post(
            'https://api.groq.com/openai/v1/chat/completions',
            headers={
                'Authorization': f'Bearer {GROQ_API_KEY}',
                'Content-Type': 'application/json'
            },
            json={
                'model': 'llama-3.3-70b-versatile',
                'messages': [
                    {
                        'role': 'system',
                        'content': (
                            'You are a Personal AI Employee assistant. '
                            'Analyze the items in the Needs_Action folder '
                            'and create a clear action plan. '
                            'Be concise and practical. '
                            'Format your response as a markdown checklist.'
                        )
                    },
                    {
                        'role': 'user',
                        'content': prompt
                    }
                ],
                'max_tokens': 1000
            }
        )
        
        data = response.json()
        return data['choices'][0]['message']['content']
        
    except Exception as e:
        logger.error(f'Groq API error: {e}')
        return f"Error calling AI: {e}"

def create_plan(items: list) -> Path:
    """Create a Plan.md file based on Needs_Action items"""
    
    if not items:
        logger.info('No items in Needs_Action — no plan needed')
        return None
    
    # Build prompt for Groq
    items_text = "\n\n".join([
        f"### {item['filename']}\n{item['content']}"
        for item in items
    ])
    
    prompt = f"""I have {len(items)} items that need attention:

{items_text}

Please create a prioritized action plan with:
1. Priority ranking (High/Medium/Low)
2. Suggested actions for each item
3. Estimated time for each action
4. Any items that need human approval"""

    logger.info(f'Calling AI to create plan for {len(items)} items...')
    
    if DRY_RUN:
        logger.info('[DRY RUN] Would call Groq AI for reasoning')
        plan_content_from_ai = f"""## AI Analysis (DRY RUN)
- Found {len(items)} items requiring attention
- Would analyze and prioritize using Groq LLaMA
- Would create action steps for each item"""
    else:
        plan_content_from_ai = call_groq(prompt)
    
    # Create Plan.md file
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    plan_path = VAULT_PATH / 'Plans' / f'PLAN_{timestamp}.md'
    
    content = f'''---
created: {datetime.now().isoformat()}
status: active
items_count: {len(items)}
dry_run: {DRY_RUN}
---

# 🧠 AI Action Plan
*Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}*

## Items Being Processed
{chr(10).join([f"- {item['filename']}" for item in items])}

## AI Recommended Actions
{plan_content_from_ai}

## Status
- [ ] Review plan
- [ ] Execute approved actions
- [ ] Move completed items to /Done

---
*Generated by AI Reasoning Engine*
'''
    
    plan_path.write_text(content, encoding='utf-8')
    logger.info(f'Plan created: {plan_path.name}')
    return plan_path

def reasoning_loop():
    """Main reasoning loop — runs every 5 minutes"""
    import time
    
    logger.info('Starting reasoning loop...')
    
    while True:
        try:
            logger.info('Reasoning cycle started...')
            
            # Get items needing attention
            items = get_needs_action_items()
            logger.info(f'Found {len(items)} items in Needs_Action')
            
            if items:
                # Create a plan
                plan_path = create_plan(items)
                if plan_path:
                    logger.info(f'Plan created: {plan_path.name}')
            else:
                logger.info('No items to process')
                
        except Exception as e:
            logger.error(f'Reasoning loop error: {e}')
        
        logger.info('Next reasoning cycle in 5 minutes...')
        time.sleep(300)

if __name__ == '__main__':
    reasoning_loop()
    